{
  "fe92201e9bb29ed8ad4b22cd37a70c51" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "13c525d7e93def8b",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='wfe', port=80): Max retries exceeded with url: /processes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ae664d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1567342917095,
        "stop" : 1567342947112,
        "duration" : 30017
      }
    } ]
  }
}